# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
	# check these on https://fabricmc.net/develop
	minecraft_version=1.21
	yarn_mappings=1.21+build.9
	loader_version=0.17.2
	loom_version=1.11-SNAPSHOT

# Fabric API
	fabric_version=0.102.0+1.21

# Mod Properties
	mod_version = 4.0
	maven_group = me.srgantmoomoo
	archives_base_name = postman

# Dependencies
	fabric_version=0.83.0+1.20
	panelstudio_version = 0.2.4
	panelstudio_versionmc = 0.2.4
	satin_version = 1.13.0
